version: '3'

services:
  app:
    image: backend-app
    ports:
      - '3000:3000'


  db:
    image: postgres:latest

    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 1221
       POSTGRES_DB: backendCRUD
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

