# Use the official PostgreSQL image as base
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 1221
ENV POSTGRES_DB backendCRUD

# Copy init SQL script to be executed during container initialization
COPY init.sql /docker-entrypoint-initdb.d/init.sql
